// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2._9_EF_Advanced_Hierarchy;

namespace _2._9_EF_Advanced_Hierarchy.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20190322103725_v2")]
    partial class v2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_2._9_EF_Advanced_Hierarchy.Exchange", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("InMDL")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(100);

                    b.Property<string>("Valute")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Exchanges");
                });

            modelBuilder.Entity("_2._9_EF_Advanced_Hierarchy.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .HasMaxLength(20);

                    b.Property<string>("LastName")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");
                });

            modelBuilder.Entity("_2._9_EF_Advanced_Hierarchy.UserIntern", b =>
                {
                    b.HasBaseType("_2._9_EF_Advanced_Hierarchy.User");

                    b.Property<string>("Speciality")
                        .HasMaxLength(20);

                    b.HasDiscriminator().HasValue("UserIntern");
                });

            modelBuilder.Entity("_2._9_EF_Advanced_Hierarchy.UserMenthor", b =>
                {
                    b.HasBaseType("_2._9_EF_Advanced_Hierarchy.User");

                    b.Property<int>("Experience");

                    b.Property<string>("Job")
                        .HasMaxLength(20);

                    b.Property<string>("Level")
                        .HasMaxLength(30);

                    b.HasDiscriminator().HasValue("UserMenthor");
                });
#pragma warning restore 612, 618
        }
    }
}
