use MyDatabase;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

--DEADLOCKING
BEGIN TRANSACTION
UPDATE Users SET [Login] = 'newLogin'
WHERE Id = 10;

WAITFOR DELAY '00:00:04';

UPDATE Themes SET [Name] = 'newEmail@mail.ru'
WHERE Id = 1;

COMMIT TRANSACTION


SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

BEGIN TRANSACTION
SELECT * FROM Users;
COMMIT TRANSACTION;


--SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
--SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
SET TRANSACTION ISOLATION LEVEL Serializable;


BEGIN TRANSACTION
SELECT * FROM Users;

WAITFOR DELAY '00:00:05';

SELECT * FROM Users;

COMMIT TRANSACTION;
