use MyDataBase;

--DEADLOCKING
BEGIN TRANSACTION

UPDATE Themes SET [Name] = 'newEmail@mail.ru'
WHERE Id = 1;

WAITFOR DELAY '00:00:03';

UPDATE Users SET [Password] = 'NewLogin'
WHERE Id = 1;

COMMIT TRANSACTION

--READ UNCOMMITTED/COMMITTED
BEGIN TRANSACTION
SELECT * FROM Users;

UPDATE Users 
SET EMail = 'Cristi007@mail.ru'
WHERE Id = 9;

WAITFOR DELAY '00:00:05';
RollBACK TRANSACTION;


SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
BEGIN TRANSACTION
--SELECT * FROM Users;

UPDATE Users 
SET EMail = 'Cristi@mail.ru'
WHERE Id = 9;
Commit TRANSACTION;


SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
BEGIN TRANSACTION

INSERT INTO Users
VALUES('ads','dsa', '1999-01-01', '+423423', 'sdasa','3215423','432@mfds');

Commit TRANSACTION;